### ISSUE TITLE
Use your own name for input context property.

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5-cskk#1]
https://github.com/naokiri/fcitx5-cskk/blob/3773af3b0ef697502d98e5f4ab6afb9d1c391afb/src/cskk.cpp#L26

I know you probably take fcitx5-skk as a reference, but the input context property name need to be globally unique. This would cause problem if cskk and skk are loaded at the same time since they both use "skkState".

It is defined as a meaningful string instead of a random string just in case any external module want to reuse it, but usually the name itself doesn't matter.

**Comment by naokiri** [comment]
Thanks a lot! I didn't know how it work deep inside.

**Comment by naokiri** [comment]
Fixed on latest master.
