### ISSUE TITLE
Use StandardPath instead of getenv to handled XDG_* environment variables

### ISSUE THREAD

**Issue by wengxt** [fcitx/fcitx5-cskk#23]
https://codedocs.xyz/fcitx/fcitx5/classfcitx_1_1StandardPath.html

This is a utility class provided by Fcitx to handle XDG_* path.

You might want to use StandardPath::Type::PkgData (which is $XDG_DATA/fcitx5) , or just  StandardPath::Type::Data.

**Comment by naokiri** [comment]
Thanks for your suggestion @wengxt TIL that method.

**Comment by naokiri** [comment]
Fixed the related part in other branch not to use xdg dirs. Closing.
